---
# file: roles/common/tasks/main.yml
- homebrew_tap:  
    name: "{{ item }}"
    state: present
  with_items: "{{ taps }}"

- homebrew:
    name: "{{ item }}"
    state: latest
  with_items: "{{ homebrews }}"

- homebrew_cask:
    name: "{{ item }}"
    state: present
  with_items: "{{ applications }}"

