---
# file: roles/common/tasks/main.yml
- name: install taps
  homebrew_tap:  tap={{ item }} state=present
  with_items: taps

- name: install applications via homebrew
  homebrew: name={{ item }} state=latest update_homebrew=yes 
  with_items: homebrews

- name: install missing casks
  homebrew_cask: name={{ item }} state=present
  with_items: applications

